### ISSUE TITLE
It does not support InceptionV3 model?

### ISSUE THREAD

**Issue by cafish** [ritchieng/tensorflow-aws-ami#8]
I'm using keras, tensorflow with inceptionV3 model. The TFAMI.v3 does not work on g2 with GPU. Although I upgraded keras, it still did not work.

Could you update the tensorflow and keras libraries, or update the AMI for InceptionV3 model?

**Comment by ritchieng** [comment]
May I know what's the error you see? Any log you can show me so I can see what's the problem. What do you mean by "does not work"? :)

**Comment by cafish** [comment]
By the way, when I just tensorflow without GPU, my code is working. But with GPU, it got problem.
Below are the main log (it got error right after the epoch 1 was started):


WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_grad.py:343 in _GatherGrad.: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-13.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
Epoch 1/25
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
.....

W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 6.77MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:975] Resource exhausted: OOM when allocating tensor with shape[32,17,17,192]


Traceback (most recent call last):
  File "train_kfold_1.py", line 112, in <module>
    trainKModel(kk)
  File "train_kfold_1.py", line 109, in trainKModel
    callbacks = [best_model])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1557, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1320, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1943, in __call__
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
KeyboardInterrupt

**Comment by ritchieng** [comment]
This is not an error relating to the installation of TensorFlow. It means the GPU ran out of memory.

Solutions:
1. Try `pkill -9 python` or `sudo pkill -9 python` to ensure all your processes have been cancelled before running the code.
2. If that fails, you need to have a bigger GPU instance as your current GPU cannot handle the model.

You can run `nvidia-smi` to check if you're maxing out your current GPU VRAM.
